import os

print("""
Cazzzzyyyyy
""")

print("""[1] pip\n[2] pip3\nWhich one do you use?""")
rn = input(">>>")
if rn == '1':
    os.system("pip install speedtest-cli")
    os.system("pip install PySocks")
    os.system("pip install cfscrape")
    os.system("pip install datetime")
    os.system("pip install ssl")
    os.system("pip install threading")
    os.system("pip install imcplib")
    os.system("pip install scapy")
elif rn == '2':
    os.system("pip3 install speedtest-cli")
    os.system("pip3 install PySocks")
    os.system("pip3 install cfscrape")
    os.system("pip3 install cloudscraper")
    os.system("pip3 install undetected_chromedriver")
    os.system("pip3 install datetime")
    os.system("pip3 install ssl")
    os.system("pip3 install threading")
    os.system("pip3 install imcplib")
    os.system("pip3 install scapy")
    os.system("pip3 install hpack")
    os.system("pip3 install HPACK")
    os.system("pip3 install fake-useragent")
    os.system("pip3 install axios")
    os.system("gcc tcp-bypass.c -o tcp-bypass")
else:
    print("?")

os.system("apt-get install nodejs")
os.system("apt-get install npm")
os.system("npm i events")
os.system("npm i http2")
os.system("npm i colors")
os.system("npm i fs")
os.system("npm i url")
os.system("npm i net")
os.system("npm i tls")
os.system("npm i os")
os.system("npm i user-agents")
os.system("npm i crypto")
os.system("npm i cloudscraper")
os.system("npm i cookie-parser")
os.system("npm i hpack")
os.system("npm i HPACK")
os.system("npm i fake-useragent")
os.system("npm i request")
os.system("npm i requests")
os.system("npm i hpack")
os.system("npm i HPACK")
os.system("npm i randomstring")
os.system("npm i cluster")
os.system("npm i cloudflare-bypasser")
os.system("npm i hcaptcha-solver")
os.system("npm i axios")
os.system("ulimit -n 999999")
os.system("chmod +x *")
os.system("sudo python3 cazzy.py")
